name: Test Secrets Configuration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Secrets
      run: |
        echo "🔍 Testando configuração das secrets..."
        
        # Verificar se as secrets existem
        if [ -n "${{ secrets.K3S_API_URL }}" ]; then
          echo "✅ K3S_API_URL está configurada"
          echo "   URL: ${{ secrets.K3S_API_URL }}"
        else
          echo "❌ K3S_API_URL NÃO está configurada"
        fi
        
        if [ -n "${{ secrets.K3S_CA_CERT }}" ]; then
          echo "✅ K3S_CA_CERT está configurada"
          echo "   Tamanho: $(echo '${{ secrets.K3S_CA_CERT }}' | wc -c) caracteres"
        else
          echo "❌ K3S_CA_CERT NÃO está configurada"
        fi
        
        if [ -n "${{ secrets.K3S_TOKEN }}" ]; then
          echo "✅ K3S_TOKEN está configurada"
          echo "   Tamanho: $(echo '${{ secrets.K3S_TOKEN }}' | wc -c) caracteres"
        else
          echo "❌ K3S_TOKEN NÃO está configurada"
        fi
        
        echo ""
        echo "🎯 INSTRUÇÕES:"
        echo "Se alguma secret não está configurada:"
        echo "1. Vá em Settings → Secrets and variables → Actions"
        echo "2. Adicione as secrets necessárias:"
        echo "   - K3S_API_URL: https://31.97.171.115:6443"
        echo "   - K3S_CA_CERT: [certificado em base64]"
        echo "   - K3S_TOKEN: [token do ServiceAccount]"
